# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
        os: [ windows-latest, ubuntu-latest ]

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: 1.5.1
      - name: Install dependencies
        run: |
          poetry lock --no-update
          poetry install
          poetry run pip install git+https://github.com/guillaumekln/faster-whisper
      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - name: Add OpenAI key to environment variables
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
      - name: Test with unittest
        working-directory: ./tests
        run: |
          poetry run python -m unittest discover -s . -p 'test_*.py'
