name: dispatch_CI

on:
  workflow_dispatch:
    inputs:
      myCommit:
        description: 'Commit SHA1'
        required: true
        default: 'undefined'
        type: string

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
        os: [ macos-latest ]

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.myCommit }}
      - uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: 1.5.1
      - name: Install dependencies
        run: |
          poetry lock --no-update
          poetry install
          poetry run pip install git+https://github.com/guillaumekln/faster-whisper
      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - name: Add OpenAI key to environment variables
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
      - name: Test with unittest
        working-directory: ./tests
        run: |
          poetry run python -m unittest discover -s . -p 'test_*.py'
