# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: 1.5.1
      - name: Install dependencies
        run: |
          poetry install
          poetry run pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          poetry run pip install git+https://github.com/m-bain/whisperx.git
      - name: Test with pytest
        run: |
          poetry run pytest tests --disable-warnings